/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#f3f0ef",
        "inverse-primary": "#fbbc00",
        "on-secondary-fixed-variant": "#474747",
        "on-tertiary-container": "#824400",
        "surface-container-low": "#f6f3f2",
        "tertiary-fixed": "#ffdcc3",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#d4c5ab",
        "on-tertiary-fixed": "#2f1500",
        "on-surface-variant": "#504532",
        "on-secondary-container": "#656464",
        "on-error": "#ffffff",
        "surface-dim": "#dcd9d9",
        "surface-container-high": "#ebe7e7",
        "on-primary-container": "#6d5000",
        "on-error-container": "#93000a",
        "on-background": "#1c1b1b",
        "tertiary-fixed-dim": "#ffb77d",
        "surface-bright": "#fcf9f8",
        "primary-container": "#ffbf00",
        "surface-container-highest": "#e5e2e1",
        "primary-fixed-dim": "#fbbc00",
        "surface": "#fcf9f8",
        "on-primary": "#ffffff",
        "secondary": "#5f5e5e",
        "error-container": "#ffdad6",
        "secondary-fixed": "#e4e2e1",
        "surface-tint": "#795900",
        "primary": "#795900",
        "outline": "#827660",
        "inverse-surface": "#313030",
        "error": "#ba1a1a",
        "on-primary-fixed": "#261a00",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#5c4300",
        "secondary-fixed-dim": "#c8c6c6",
        "secondary-container": "#e4e2e1",
        "on-tertiary-fixed-variant": "#6e3900",
        "background": "#fcf9f8",
        "surface-variant": "#e5e2e1",
        "on-surface": "#1c1b1b",
        "on-tertiary": "#ffffff",
        "surface-container": "#f0edec",
        "tertiary": "#904d00",
        "tertiary-container": "#ffbb85",
        "primary-fixed": "#ffdfa0",
        "on-secondary-fixed": "#1b1c1c"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
